services:
  - type: web
    name: backend-apex
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: NEXT_PUBLIC_PIX_KEY
        value: 09311538400
      - key: FULFILLMENT_WEBHOOK_URL
        value: https://api.dropi.co/v1/webhook/orders?key=DRKGcbNn2Y
      - key: SUPPLIER_API_KEY
        value: DRKGcbNn2Y
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ADMIN_SECRET
        value: quantum-2026
